export const HotelList =[
    {
        id:"1",
        ownerName: "hanjisung",
        ownerPhone: "08123456789",
        petName: "berry",
        species: "Dog",
        breed: "Poodle",
        gender: "female",
        weight: "0-5kg",
        booking: "26/04/23",
        pickup: "27/04/23",
    },
    {
        id:"2",
        ownerName: "leeknow",
        ownerPhone: "08123456789",
        petName: "dori",
        species: "cat",
        breed: "white-orange",
        gender: "male",
        weight: "0-5kg",
        booking: "26/04/23",
        pickup: "27/04/23",
    },
]
